export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_OTP: "INVALID_OTP",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACCOUNT_NOT_FOUND_PHONE: "ACCOUNT_NOT_FOUND_PHONE",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
  RATE_LIMIT: "RATE_LIMIT",
  VALIDATION: "VALIDATION",
  SERVER: "SERVER",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  SESSION_FAILED: "SESSION_FAILED",
  OTP_SEND_FAILED: "OTP_SEND_FAILED",
  OTP_DELIVERY_UNAVAILABLE: "OTP_DELIVERY_UNAVAILABLE",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  CURRENT_PASSWORD_REQUIRED: "CURRENT_PASSWORD_REQUIRED",
  CURRENT_PASSWORD_INVALID: "CURRENT_PASSWORD_INVALID",
  TOTP_REQUIRED: "TOTP_REQUIRED",
  TOTP_INVALID: "TOTP_INVALID",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

export const NETWORK_ERROR_CODES = {
  NETWORK: "NETWORK",
  TIMEOUT: "TIMEOUT",
  BAD_GATEWAY: "BAD_GATEWAY",
  MALFORMED: "MALFORMED",
  CHUNK_LOAD: "CHUNK_LOAD",
} as const;

export type NetworkErrorCode = (typeof NETWORK_ERROR_CODES)[keyof typeof NETWORK_ERROR_CODES];
